steps:
  - plugin: Script
    name: Upgrade PHP
    script: |
      apt-get update
      apt-get install software-properties-common
      add-apt-repository ppa:ondrej/php -y
      apt-get update
      apt-get install php7.0
      apt-get install php7.0-mysql
      php -v
