steps:
  - plugin: Script
    name: Upgrade PHP
    script: |
      apt-get update -y
      apt-get install software-properties-common -y
      add-apt-repository ppa:ondrej/php -y
      apt-get update -y
      apt-get install php7.0 -y
      apt-get install php7.0-mysql -y
      php -v
