steps:
  - plugin: Script
    name: Upgrade Java
    script: |
      wget https://archive.apache.org/dist/lucene/solr/6.1.0/solr-6.1.0.tgz
      tar xzf solr-6.1.0.tgz
      mkdir -p solr-6.1.0/server/collection1/conf
      wget http://ftp.drupal.org/files/projects/search_api_solr-8.x-1.x-dev.tar.gz
      tar xzf search_api_solr-8.x-1.x-dev.tar.gz
      sudo cp -a search_api_solr/solr-conf/6.x/. solr-6.1.0/server/collection1/conf/
      chown www-data:www-data -R solr-6.1.0/server/collection1/conf
      ./solr-6.1.0/bin/solr start
