steps:
  - plugin: Script
    name: Upgrade PHP
    script: |
      apt-get update -y
      apt-get install software-properties-common -y
      LC_ALL=C.UTF-8 add-apt-repository ppa:openjdk-r/ppa -y
      apt-get update
      apt-get install openjdk-8-jdk -f
      apt-get install openjdk-8-jre -f
      java -version
