steps:
  - plugin: Script
    name: Upgrade PHP
    script: |
      add-apt-repository ppa:openjdk-r/ppa -y
      apt-get update
      apt-get install openjdk-8-jdk
      apt-get install openjdk-8-jre
      java -version
